### ISSUE TITLE
GameSolver guessed duplicate number

### ISSUE THREAD

**Issue by kykungz** [OOP2018/guessing-game-wisaTong#1]
GameSolver guessed duplicate number.

<img width="218" alt="screen shot 2561-01-17 at 16 37 29" src="https://user-images.githubusercontent.com/9304909/35035721-dc13633c-fba4-11e7-9118-e2fde08fb213.png">

Hint: `range` is not updated before creating new `solution` after player guessed.
https://github.com/OOP2018/guessing-game-wisaTong/blob/7f04e44765039284923cd317d8a65e7a92b4e2f0/src/GameSolver.java#L31

**Comment by wisaTong** [comment]
GameSolver did not guessed duplicate number. GameSolver can works fine individually and range update every loop because I declared new range every loop, see

 `while (!correct) {
int range = upper - lower;
.
.
.
}`

**Comment by kykungz** [comment]
Try setting the `secret` to be `6`, and print the GameSolver's `solution` each time.
You will see that it used `7` guesses instead of `4`
```
// Your GameSolver's guessing sequence
50
50
25
25
12
12
6
// game.getCount() => 7
```
```
// What it should be
50
25
12
6
// game.getCount() => 4
```

**Comment by wisaTong** [comment]
Oh shit, get it now. Fixed. Thank you very much.
Sorry for arrogant reply tho.

**Comment by kykungz** [comment]
No problem! 💯
Checked, works correctly, you can now close this issue!
